[2024-11-25T00:00:43.313+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-25T00:00:43.325+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2024-11-24T00:00:00+00:00 [queued]>
[2024-11-25T00:00:43.329+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2024-11-24T00:00:00+00:00 [queued]>
[2024-11-25T00:00:43.329+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-25T00:00:43.334+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2024-11-24 00:00:00+00:00
[2024-11-25T00:00:43.339+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=38656) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-25T00:00:43.339+0000] {standard_task_runner.py:72} INFO - Started process 38657 to run task
[2024-11-25T00:00:43.340+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2024-11-24T00:00:00+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpauqb5b97']
[2024-11-25T00:00:43.341+0000] {standard_task_runner.py:105} INFO - Job 94: Subtask local_to_gcs_task
[2024-11-25T00:00:43.370+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2024-11-24T00:00:00+00:00 [running]> on host 4cef807186dc
[2024-11-25T00:00:43.423+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='local_to_gcs_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-24T00:00:00+00:00'
[2024-11-25T00:00:43.424+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-25T00:00:43.974+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-25T00:00:44.060+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-25T00:00:44.088+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, run_id=scheduled__2024-11-24T00:00:00+00:00, execution_date=20241124T000000, start_date=20241125T000043, end_date=20241125T000044
[2024-11-25T00:00:44.203+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-25T00:00:44.228+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T00:00:44.229+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
