[2024-11-24T00:00:52.865+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-24T00:00:52.877+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2024-11-23T00:00:00+00:00 [queued]>
[2024-11-24T00:00:52.881+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2024-11-23T00:00:00+00:00 [queued]>
[2024-11-24T00:00:52.881+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-24T00:00:52.887+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2024-11-23 00:00:00+00:00
[2024-11-24T00:00:52.892+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=37986) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-24T00:00:52.894+0000] {standard_task_runner.py:72} INFO - Started process 37987 to run task
[2024-11-24T00:00:52.893+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2024-11-23T00:00:00+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp3w2m7s58']
[2024-11-24T00:00:52.895+0000] {standard_task_runner.py:105} INFO - Job 89: Subtask local_to_gcs_task
[2024-11-24T00:00:52.922+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2024-11-23T00:00:00+00:00 [running]> on host 4cef807186dc
[2024-11-24T00:00:52.999+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='local_to_gcs_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-23T00:00:00+00:00'
[2024-11-24T00:00:53.000+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-24T00:00:53.564+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-24T00:00:53.585+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-24T00:00:53.587+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, run_id=scheduled__2024-11-23T00:00:00+00:00, execution_date=20241123T000000, start_date=20241124T000052, end_date=20241124T000053
[2024-11-24T00:00:53.642+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-24T00:00:53.660+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-24T00:00:53.661+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
