[2024-12-06T21:30:05.032+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-06T21:30:05.041+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: homework_zone_dag.delete_dataset manual__2024-12-06T21:29:49.738876+00:00 [queued]>
[2024-12-06T21:30:05.046+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: homework_zone_dag.delete_dataset manual__2024-12-06T21:29:49.738876+00:00 [queued]>
[2024-12-06T21:30:05.047+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-06T21:30:05.053+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): delete_dataset> on 2024-12-06 21:29:49.738876+00:00
[2024-12-06T21:30:05.062+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5279) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-06T21:30:05.063+0000] {standard_task_runner.py:72} INFO - Started process 5280 to run task
[2024-12-06T21:30:05.062+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'homework_zone_dag', 'delete_dataset', 'manual__2024-12-06T21:29:49.738876+00:00', '--job-id', '151', '--raw', '--subdir', 'DAGS_FOLDER/homework_zone_dag.py', '--cfg-path', '/tmp/tmp5t21ct_g']
[2024-12-06T21:30:05.064+0000] {standard_task_runner.py:105} INFO - Job 151: Subtask delete_dataset
[2024-12-06T21:30:05.103+0000] {task_command.py:467} INFO - Running <TaskInstance: homework_zone_dag.delete_dataset manual__2024-12-06T21:29:49.738876+00:00 [running]> on host 39ecaeffba2c
[2024-12-06T21:30:05.142+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='homework_zone_dag' AIRFLOW_CTX_TASK_ID='delete_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-12-06T21:29:49.738876+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-06T21:29:49.738876+00:00'
[2024-12-06T21:30:05.143+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-06T21:30:05.150+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-06T21:30:05.151+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'rm /opt/***/zones.csv']
[2024-12-06T21:30:05.157+0000] {subprocess.py:99} INFO - Output:
[2024-12-06T21:30:05.160+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2024-12-06T21:30:05.174+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-06T21:30:05.174+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=homework_zone_dag, task_id=delete_dataset, run_id=manual__2024-12-06T21:29:49.738876+00:00, execution_date=20241206T212949, start_date=20241206T213005, end_date=20241206T213005
[2024-12-06T21:30:05.208+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-06T21:30:05.218+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-06T21:30:05.218+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
