[2024-12-05T18:08:40.820+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-05T18:08:40.850+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: LocalIngestionDag.ingest scheduled__2021-05-02T06:00:00+00:00 [queued]>
[2024-12-05T18:08:40.883+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: LocalIngestionDag.ingest scheduled__2021-05-02T06:00:00+00:00 [queued]>
[2024-12-05T18:08:40.884+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-05T18:08:40.919+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): ingest> on 2021-05-02 06:00:00+00:00
[2024-12-05T18:08:40.937+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1608) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-05T18:08:40.941+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2021-05-02T06:00:00+00:00', '--job-id', '187', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpe5q2xkc2']
[2024-12-05T18:08:40.945+0000] {standard_task_runner.py:105} INFO - Job 187: Subtask ingest
[2024-12-05T18:08:40.944+0000] {standard_task_runner.py:72} INFO - Started process 1650 to run task
[2024-12-05T18:08:41.061+0000] {task_command.py:467} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2021-05-02T06:00:00+00:00 [running]> on host 073dea24e113
[2024-12-05T18:08:41.165+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='LocalIngestionDag' AIRFLOW_CTX_TASK_ID='ingest' AIRFLOW_CTX_EXECUTION_DATE='2021-05-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-05-02T06:00:00+00:00'
[2024-12-05T18:08:41.166+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-05T18:08:41.174+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-05T18:08:41.176+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'pwd"']
[2024-12-05T18:08:41.181+0000] {subprocess.py:99} INFO - Output:
[2024-12-05T18:08:41.181+0000] {subprocess.py:106} INFO - /usr/bin/bash: -c: line 1: unexpected EOF while looking for matching `"'
[2024-12-05T18:08:41.182+0000] {subprocess.py:110} INFO - Command exited with return code 2
[2024-12-05T18:08:41.189+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-12-05T18:08:41.193+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, run_id=scheduled__2021-05-02T06:00:00+00:00, execution_date=20210502T060000, start_date=20241205T180840, end_date=20241205T180841
[2024-12-05T18:08:41.202+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-05T18:08:41.202+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 187 for task ingest (Bash command failed. The command returned a non-zero exit code 2.; 1650)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-12-05T18:08:41.234+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-05T18:08:41.247+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-05T18:08:41.248+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-05T20:36:38.171+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-05T20:36:38.181+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: LocalIngestionDag.ingest scheduled__2021-05-02T06:00:00+00:00 [queued]>
[2024-12-05T20:36:38.186+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: LocalIngestionDag.ingest scheduled__2021-05-02T06:00:00+00:00 [queued]>
[2024-12-05T20:36:38.186+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-05T20:36:38.192+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): ingest> on 2021-05-02 06:00:00+00:00
[2024-12-05T20:36:38.196+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=702) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-05T20:36:38.197+0000] {standard_task_runner.py:72} INFO - Started process 703 to run task
[2024-12-05T20:36:38.198+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2021-05-02T06:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmp545lwguz']
[2024-12-05T20:36:38.199+0000] {standard_task_runner.py:105} INFO - Job 18: Subtask ingest
[2024-12-05T20:36:38.229+0000] {task_command.py:467} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2021-05-02T06:00:00+00:00 [running]> on host cf87bc668ac5
[2024-12-05T20:36:38.273+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='LocalIngestionDag' AIRFLOW_CTX_TASK_ID='ingest' AIRFLOW_CTX_EXECUTION_DATE='2021-05-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-05-02T06:00:00+00:00'
[2024-12-05T20:36:38.274+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-05T20:36:38.282+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-05T20:36:38.282+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'ls /opt/***']
[2024-12-05T20:36:38.287+0000] {subprocess.py:99} INFO - Output:
[2024-12-05T20:36:38.289+0000] {subprocess.py:106} INFO - ***.cfg
[2024-12-05T20:36:38.289+0000] {subprocess.py:106} INFO - config
[2024-12-05T20:36:38.289+0000] {subprocess.py:106} INFO - dags
[2024-12-05T20:36:38.289+0000] {subprocess.py:106} INFO - logs
[2024-12-05T20:36:38.289+0000] {subprocess.py:106} INFO - output.parquet
[2024-12-05T20:36:38.290+0000] {subprocess.py:106} INFO - output_2021-01.parquet
[2024-12-05T20:36:38.290+0000] {subprocess.py:106} INFO - output_2021-02.parquet
[2024-12-05T20:36:38.290+0000] {subprocess.py:106} INFO - output_2021-03.parquet
[2024-12-05T20:36:38.290+0000] {subprocess.py:106} INFO - output_2021-04.parquet
[2024-12-05T20:36:38.290+0000] {subprocess.py:106} INFO - output_2021-05.parquet
[2024-12-05T20:36:38.290+0000] {subprocess.py:106} INFO - plugins
[2024-12-05T20:36:38.290+0000] {subprocess.py:106} INFO - requirements.txt
[2024-12-05T20:36:38.290+0000] {subprocess.py:106} INFO - webserver_config.py
[2024-12-05T20:36:38.290+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2024-12-05T20:36:38.304+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-05T20:36:38.305+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=LocalIngestionDag, task_id=ingest, run_id=scheduled__2021-05-02T06:00:00+00:00, execution_date=20210502T060000, start_date=20241205T203638, end_date=20241205T203638
[2024-12-05T20:36:38.339+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-05T20:36:38.351+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-05T20:36:38.352+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-05T23:10:44.571+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-05T23:10:44.776+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: LocalIngestionDag.ingest scheduled__2021-05-02T06:00:00+00:00 [queued]>
[2024-12-05T23:10:44.783+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: LocalIngestionDag.ingest scheduled__2021-05-02T06:00:00+00:00 [queued]>
[2024-12-05T23:10:44.783+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-05T23:10:44.792+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): ingest> on 2021-05-02 06:00:00+00:00
[2024-12-05T23:10:44.806+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2021-05-02T06:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpnx46ooei']
[2024-12-05T23:10:44.811+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask ingest
[2024-12-05T23:10:44.811+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=115) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-05T23:10:44.813+0000] {standard_task_runner.py:72} INFO - Started process 129 to run task
[2024-12-05T23:10:44.865+0000] {task_command.py:467} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2021-05-02T06:00:00+00:00 [running]> on host 39ecaeffba2c
[2024-12-05T23:10:44.920+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='LocalIngestionDag' AIRFLOW_CTX_TASK_ID='ingest' AIRFLOW_CTX_EXECUTION_DATE='2021-05-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-05-02T06:00:00+00:00'
[2024-12-05T23:10:44.922+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-05T23:10:44.933+0000] {logging_mixin.py:190} INFO - root root pgdatabase 5432 ny_taxi ??? /opt/***/output_2021-05.parquet
[2024-12-05T23:10:44.941+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-05T23:10:44.949+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-05T23:10:44.949+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=LocalIngestionDag, task_id=ingest, run_id=scheduled__2021-05-02T06:00:00+00:00, execution_date=20210502T060000, start_date=20241205T231044, end_date=20241205T231044
[2024-12-05T23:10:45.000+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-05T23:10:45.010+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-05T23:10:45.012+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
