[2024-12-05T18:08:40.733+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-05T18:08:40.792+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: LocalIngestionDag.ingest scheduled__2021-04-02T06:00:00+00:00 [queued]>
[2024-12-05T18:08:40.806+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: LocalIngestionDag.ingest scheduled__2021-04-02T06:00:00+00:00 [queued]>
[2024-12-05T18:08:40.806+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-05T18:08:40.845+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): ingest> on 2021-04-02 06:00:00+00:00
[2024-12-05T18:08:40.862+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1597) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-05T18:08:40.865+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2021-04-02T06:00:00+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpfst3bh2f']
[2024-12-05T18:08:40.872+0000] {standard_task_runner.py:105} INFO - Job 186: Subtask ingest
[2024-12-05T18:08:40.870+0000] {standard_task_runner.py:72} INFO - Started process 1644 to run task
[2024-12-05T18:08:40.974+0000] {task_command.py:467} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2021-04-02T06:00:00+00:00 [running]> on host 073dea24e113
[2024-12-05T18:08:41.102+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='LocalIngestionDag' AIRFLOW_CTX_TASK_ID='ingest' AIRFLOW_CTX_EXECUTION_DATE='2021-04-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-04-02T06:00:00+00:00'
[2024-12-05T18:08:41.107+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-05T18:08:41.123+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-05T18:08:41.123+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'pwd"']
[2024-12-05T18:08:41.141+0000] {subprocess.py:99} INFO - Output:
[2024-12-05T18:08:41.144+0000] {subprocess.py:106} INFO - /usr/bin/bash: -c: line 1: unexpected EOF while looking for matching `"'
[2024-12-05T18:08:41.146+0000] {subprocess.py:110} INFO - Command exited with return code 2
[2024-12-05T18:08:41.172+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-12-05T18:08:41.176+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, run_id=scheduled__2021-04-02T06:00:00+00:00, execution_date=20210402T060000, start_date=20241205T180840, end_date=20241205T180841
[2024-12-05T18:08:41.187+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-05T18:08:41.188+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 186 for task ingest (Bash command failed. The command returned a non-zero exit code 2.; 1644)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-12-05T18:08:41.200+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-05T18:08:41.209+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-05T18:08:41.210+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-05T20:36:36.696+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-05T20:36:36.718+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: LocalIngestionDag.ingest scheduled__2021-04-02T06:00:00+00:00 [queued]>
[2024-12-05T20:36:36.728+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: LocalIngestionDag.ingest scheduled__2021-04-02T06:00:00+00:00 [queued]>
[2024-12-05T20:36:36.728+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-05T20:36:36.755+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): ingest> on 2021-04-02 06:00:00+00:00
[2024-12-05T20:36:36.760+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=691) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-05T20:36:36.764+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2021-04-02T06:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpsbxdzsgs']
[2024-12-05T20:36:36.767+0000] {standard_task_runner.py:72} INFO - Started process 692 to run task
[2024-12-05T20:36:36.767+0000] {standard_task_runner.py:105} INFO - Job 15: Subtask ingest
[2024-12-05T20:36:36.801+0000] {task_command.py:467} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2021-04-02T06:00:00+00:00 [running]> on host cf87bc668ac5
[2024-12-05T20:36:36.854+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='LocalIngestionDag' AIRFLOW_CTX_TASK_ID='ingest' AIRFLOW_CTX_EXECUTION_DATE='2021-04-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-04-02T06:00:00+00:00'
[2024-12-05T20:36:36.856+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-05T20:36:36.868+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-05T20:36:36.869+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'ls /opt/***']
[2024-12-05T20:36:36.876+0000] {subprocess.py:99} INFO - Output:
[2024-12-05T20:36:36.879+0000] {subprocess.py:106} INFO - ***.cfg
[2024-12-05T20:36:36.879+0000] {subprocess.py:106} INFO - config
[2024-12-05T20:36:36.880+0000] {subprocess.py:106} INFO - dags
[2024-12-05T20:36:36.880+0000] {subprocess.py:106} INFO - logs
[2024-12-05T20:36:36.880+0000] {subprocess.py:106} INFO - output.parquet
[2024-12-05T20:36:36.880+0000] {subprocess.py:106} INFO - output_2021-01.parquet
[2024-12-05T20:36:36.880+0000] {subprocess.py:106} INFO - output_2021-02.parquet
[2024-12-05T20:36:36.881+0000] {subprocess.py:106} INFO - output_2021-03.parquet
[2024-12-05T20:36:36.881+0000] {subprocess.py:106} INFO - output_2021-04.parquet
[2024-12-05T20:36:36.882+0000] {subprocess.py:106} INFO - output_2021-05.parquet
[2024-12-05T20:36:36.882+0000] {subprocess.py:106} INFO - plugins
[2024-12-05T20:36:36.883+0000] {subprocess.py:106} INFO - requirements.txt
[2024-12-05T20:36:36.883+0000] {subprocess.py:106} INFO - webserver_config.py
[2024-12-05T20:36:36.883+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2024-12-05T20:36:36.902+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-05T20:36:36.902+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=LocalIngestionDag, task_id=ingest, run_id=scheduled__2021-04-02T06:00:00+00:00, execution_date=20210402T060000, start_date=20241205T203636, end_date=20241205T203636
[2024-12-05T20:36:36.950+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-05T20:36:36.966+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-05T20:36:36.967+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-05T23:10:44.560+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-05T23:10:44.577+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: LocalIngestionDag.ingest scheduled__2021-04-02T06:00:00+00:00 [queued]>
[2024-12-05T23:10:44.586+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: LocalIngestionDag.ingest scheduled__2021-04-02T06:00:00+00:00 [queued]>
[2024-12-05T23:10:44.587+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-05T23:10:44.600+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): ingest> on 2021-04-02 06:00:00+00:00
[2024-12-05T23:10:44.608+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=111) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-05T23:10:44.611+0000] {standard_task_runner.py:72} INFO - Started process 124 to run task
[2024-12-05T23:10:44.610+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2021-04-02T06:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmp3u6qkuh6']
[2024-12-05T23:10:44.616+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask ingest
[2024-12-05T23:10:44.674+0000] {task_command.py:467} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2021-04-02T06:00:00+00:00 [running]> on host 39ecaeffba2c
[2024-12-05T23:10:44.962+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='LocalIngestionDag' AIRFLOW_CTX_TASK_ID='ingest' AIRFLOW_CTX_EXECUTION_DATE='2021-04-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-04-02T06:00:00+00:00'
[2024-12-05T23:10:44.963+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-05T23:10:44.970+0000] {logging_mixin.py:190} INFO - root root pgdatabase 5432 ny_taxi ??? /opt/***/output_2021-04.parquet
[2024-12-05T23:10:44.976+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-05T23:10:44.982+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-05T23:10:44.982+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=LocalIngestionDag, task_id=ingest, run_id=scheduled__2021-04-02T06:00:00+00:00, execution_date=20210402T060000, start_date=20241205T231044, end_date=20241205T231044
[2024-12-05T23:10:45.007+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-05T23:10:45.016+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-05T23:10:45.021+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
